const actionTypes = {
  // alerts
  SET_ALERT: "SET_ALERT",
  REMOVE_ALERT: "REMOVE_ALERT",
  REMOVE_ALERT_FASTER: "REMOVE_ALERT_FASTER",
  // auth
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  USER_LOADED: "USER_LOADED",
  AUTH_ERROR: "AUTH_ERROR",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGOUT: "LOGOUT",
  // profile
  GET_PROFILE: "GET_PROFILE",
  GET_PROFILES: "GET_PROFILES",
  PROFILE_ERROR: "PROFILE_ERROR",
  CLEAR_PROFILE: "CLEAR_PROFILE",
  UPDATE_PROFILE: "UPDATE_PROFILE",
  GET_REPOS: "GET_REPOS",
  // account
  ACCOUNT_DELETED: "ACCOUNT_DELETED",
  // posts
  GET_POSTS: "GET_POSTS",
  GET_POST: "GET_POST",
  POST_ERROR: "POST_ERROR",
  UPDATE_LIKES: "UPDATE_LIKES",
  DELETE_POST: "DELETE_POST",
  ADD_POST: "ADD_POST",
  ADD_COMMENT: "ADD_COMMENT",
  REMOVE_COMMENT: "REMOVE_COMMENT",
};

export default actionTypes;
